"""Generate docs from the registry and the freshly generated data (run after `make data`):

    docs/AGENT_CATALOG.md  — from backend/app/agents/registry.py
    docs/DEMO_SCRIPT.md    — Section 11 script with the actual numbers of the generated tenants
    data_gen/README.md     — tables, volumes and planted anomalies with counts per tenant
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "backend"), str(ROOT)]

from app.agents.registry import catalog_markdown  # noqa: E402
from app.config import demo_today  # noqa: E402
from app.db import models  # noqa: E402
from app.db.session import Repo  # noqa: E402
from app.services.metrics import latest_output  # noqa: E402


def months(days: int) -> int:
    return round(days / 30.4)


def facts(t: str) -> dict:
    r = Repo(t)
    out = {}
    d = latest_output(r, "pf.app_discovery")
    nf = [f for f in d["findings"] if f["type"] == "new_app"]
    out["shadow"] = len(nf)
    out["shadow_genai_expense"] = sum(1 for f in nf if f.get("genai") and f.get("paid_via_expense"))
    out["genai_names"] = [f["candidate_name"] for f in nf if f.get("genai")]
    out["retired_candidates"] = [g["canonical"] for g in r.all("gt_shadow_it") if g["truth"] == "retired"]
    out["cmdb_dup"] = sum(1 for f in d["findings"] if f["type"] == "cmdb_duplicate")
    out["cmdb_stale"] = sum(1 for f in d["findings"] if f["type"] == "cmdb_stale")
    out["expense_ref"] = (d["findings"] and next((f["source_refs"][0]["record_id"] for f in nf if f.get("paid_via_expense")), ""))
    lc = latest_output(r, "pf.lifecycle_watcher")
    eos = [f for f in lc["findings"] if f["type"] == "vendor_eos"]
    out["eos"] = eos
    traps = [f for f in lc["findings"] if f["type"] == "contract_renewal" and f.get("auto_renew") and (f.get("utilization") or 1) < 0.3]
    out["traps"] = traps
    ov = latest_output(r, "pf.overlap_finder")
    out["overlaps"] = ov["findings"]
    rk = latest_output(r, "dai.ai_risk_classifier")
    out["tiers"] = {f["title"]: f["tier"] for f in rk["findings"]}
    out["tier_counts"] = Counter(f["tier"] for f in rk["findings"])
    reg = latest_output(r, "dai.model_agent_registry_steward")
    out["assets"] = reg["facts"] if "facts" in reg else None
    out["n_assets"] = r.count("ai_assets")
    out["n_unreg"] = sum(1 for a in r.all("ai_assets") if not a["registered"])
    dr = latest_output(r, "app.design_review")
    out["designs"] = {f["title"]: f for f in dr["findings"]}
    dd = latest_output(r, "app.drift_detector")
    out["boundary"] = [f for f in dd["findings"] if f["type"] == "boundary_violation"]
    cur = latest_output(r, "ea.capability_curator")
    out["caps"] = {f["name"]: f for f in cur["findings"]}
    inv = latest_output(r, "ea.investment_traceability")
    orphan = sum(f["budget_usd"] for f in inv["findings"] if f["status"] == "orphan")
    total = sum(p["budget_usd"] for p in r.all("projects"))
    out["orphan_pct"] = round(100 * orphan / total)
    out["unfunded"] = [f["statement"] for f in inv["findings"] if f["status"] == "unfunded"]
    cost = latest_output(r, "pf.cost_license_optimizer")
    out["cost"] = cost["findings"]
    out["apps"] = {a["name"]: a for a in r.all("applications")}
    return out


def demo_script() -> str:
    n, m = facts("northgrid"), facts("meridian")
    oms = next((e for e in n["eos"] if e["name"] == "OutageWorks OMS"), None)
    trap = next((t for t in n["traps"] if t["name"] == "Vizora Analytics"), n["traps"][0] if n["traps"] else None)
    docs = next((o for o in n["overlaps"] if "TeamSpace Docs" in o["app_names"]), None)
    uis = n["designs"].get("Customer Usage Insights service")
    om = n["caps"].get("Outage Management")
    med = next((e for e in m["eos"] if "MedLink" in e["name"]), None)
    billing = next((o for o in m["overlaps"] if "Coastline Billing (Legacy)" in o["app_names"]), None)
    crm = next((o for o in m["overlaps"] if "Helios CRM Consumer" in o["app_names"]), None)
    charge = next((c for c in m["cost"] if c["type"] == "above_market_price"), None)
    lines = f"""# Demo Script (15 minutes)

*Generated by `make docs` from the synthetic data (seed 42, demo date {demo_today().isoformat()}). Numbers below are what the
UI shows on a fresh `make reset`. UI labels in **bold** match the screens.*

**Setup:** `make demo` → open http://localhost:5173 (or http://localhost:8000 for the built UI). Tenant **NorthGrid Energy**,
**Acting as** Avery Lindqvist — Principal Architect, badge **Mock LLM**.

## 1. Problem (1 min) — Ingested Sources
Open **Ingested Sources**. "Here is what we connected read-only: SSO logs, invoices and expense reports, cloud billing, CMDB,
Git repositories, the data catalogue, the model registry." Open **SSO identity provider** and **CMDB** cards to show the
inconsistent names (`TEAMSPACE DOCS`, `teamspace-docs-prod`, `NG-…`). Toggle **show what we planted** only if asked.

## 2. Portfolio discovery (3 min) — Portfolio › Discovery
1. Click **Re-run** on *Application Discovery* (autonomy **Observe · L1**). Result: **{n['shadow']} shadow IT candidates**,
   **{n['shadow_genai_expense']} generative-AI tools paid through expense reports** ({', '.join(n['genai_names'])}),
   **{n['cmdb_dup']} CMDB duplicates** and **{n['cmdb_stale']} stale CIs** (retired apps still listed), each with a confidence badge.
2. Click an evidence chip on a GenAI candidate (e.g. `[{n['expense_ref']}]`) → the drawer shows the raw invoice/expense line and which agents used it.
3. Click **Send to owners for confirmation** → candidates become approval items for app owners.
4. Switch **Acting as** to an **App Owner** (e.g. Priya Raman) → **Approvals** → approve two candidates, reject
   *{n['retired_candidates'][0] if n['retired_candidates'] else 'one'}* ("retired tool").
5. **Audit** → filter subject by the candidate id → the decision and graph update are logged.

## 3. Savings (2 min) — Portfolio › Overlaps / Lifecycle / Savings
- **Overlaps**: {len(docs['app_ids']) if docs else 3} document-management systems ({', '.join(docs['app_names']) if docs else ''}) with
  **{docs['survivor_name'] if docs else 'TeamSpace Docs'}** recommended as survivor (~${docs['est_savings_usd']:,.0f}/yr).
- **Lifecycle**: **OutageWorks OMS** vendor end of support in **{months(oms['days_remaining']) if oms else 7} months** ({oms['days_remaining'] if oms else '-'} days);
  **{trap['name'] if trap else 'Vizora Analytics'}** auto-renews in **{trap['days_remaining'] if trap else '-'} days** at **{round((trap['utilization'] or 0) * 100) if trap else '-'}% seat utilisation**.
- On the document-management cluster click **Build business case** → one-page case. Switch **Acting as** to the **CIO** → approve it in
  **Approvals** → **Dashboard** savings tile (*approved*) increases.

## 4. AI governance (3 min) — AI Governance
- **Intake backlog**: ranked by value × feasibility × data readiness.
- **Classify risk** on *Dynamic pricing recommendation* → **{n['tiers'].get('Dynamic pricing recommendation', 'high').upper()}** (AIR-H4: automated decision with
  effect on customers) with required controls. *Grid operator GenAI knowledge assistant* → **{n['tiers'].get('Grid operator GenAI knowledge assistant', 'high').upper()}** (AIR-H3, safety-relevant).
  *Covert employee sentiment monitoring* → **BLOCKED** (AIR-U1). *Vegetation encroachment detection from imagery* → **{n['tiers'].get('Vegetation encroachment detection from imagery', 'minimal').upper()}**.
- Switch to the **Risk Officer** → approve two tiers in **Approvals** (the principal architect cannot sign off AI risk).
- **AI asset registry**: **{n['n_assets']} AI assets, {n['n_unreg']} unregistered** (shadow AI, including expense-paid copilots).
- **Generate evidence pack** → *State PUC customer data privacy rule* → markdown + JSON with controls, findings, approvals and approvers.

## 5. Application architecture (3 min) — Application Architecture
- **Design reviews** → open **Customer Usage Insights service** → verdict **{(uis['verdict'] if uis else 'changes_required').replace('_', ' ')}** with concerns
  {', '.join(c['standard_id'] for c in uis['concerns']) if uis else ''} (direct DB link to the CIS billing database, unapproved GenAI vendor, missing
  classification, polling MDM tables) and a suggestion to reuse the **Customer Lookup API**.
- **Drift**: **{len(n['boundary'])} IT/OT boundary violations** highlighted in red on the actual-vs-intended diagram → approve
  **create remediation ticket** as the **Security Architect** → simulated Jira ticket (agent at L3).
- **ADRs**: publish a draft generated from a Slack thread (as **Tech Lead**).

## 6. Enterprise architecture (2 min) — Enterprise Architecture
- **Capability heat map**: *Outage Management* importance {om['importance'] if om else 5}, maturity {om['maturity'] if om else 2}, heat {om['heat_score'] if om else 15},
  **{om['app_count'] if om else '-'} applications** realise it.
- **Investment alignment**: **{n['orphan_pct']}% of project budget has no strategic goal**; unfunded goals: {'; '.join(n['unfunded'])}.
- **Impact analysis** preset **GIS vendor exits market** → affected applications, capabilities, datasets, AI and people.
- **Roadmap scenarios**: three scenarios; adopt **Risk-first** (as **CIO**).

## 7. Copilot + switch tenant (1 min)
- **Copilot**: ask *"Who owns meter data and what AI uses it?"* → cited answer and lineage diagram.
- Switch tenant to **Meridian Telecom**: same agents, different story —
  two billing systems post-merger (**{', '.join(billing['app_names']) if billing else ''}**, survivor {billing['survivor_name'] if billing else ''}),
  two CRMs ({', '.join(crm['app_names']) if crm else ''}), {len(m['boundary'])} BSS/OSS shared-DB violations,
  **Next-best-offer** tiered **{m['tiers'].get('Next-best-offer', 'high').upper()}**, legacy mediation EOS in **{months(med['days_remaining']) if med else 6} months**,
  charging contract at **2x market** ({charge['evidence'] if charge else ''}).
  Show the **Dashboard** for Meridian.

### Copilot suggested questions
NorthGrid and Meridian each have 12 suggested questions on the Copilot page (see `data_gen/catalogs/*.yaml → copilot_questions`).

### Preset impact triggers
NorthGrid: GIS vendor exit; new PUC data-access mandate; acquire a neighbouring co-op (adds 300k customers); OMS end of support.
Meridian: merge the two billing systems; regulator bans fully automated credit decisions; legacy mediation retirement; new data residency law.
"""
    return lines


def data_readme() -> str:
    from data_gen.generators.core import load_yaml  # noqa: F401

    lines = ["# Synthetic data generator", "", "```", "python -m data_gen.generate --tenant northgrid --seed 42 --out data/northgrid.db",
             "python -m data_gen.generate --tenant meridian --seed 42 --out data/meridian.db", "python -m data_gen.generate --all", "```", "",
             "Deterministic: same seed + same `DEMO_TODAY` → identical data. All dates are relative to `DEMO_TODAY` (default today).",
             "Industry content is hand-authored in `catalogs/utilities.yaml`, `catalogs/telecom.yaml`, `catalogs/common.yaml` and",
             "`catalogs/ai_risk_rules.yaml`; generators in `generators/` add the long tail and the planted anomalies.",
             "Raw per-source exports (`sso.csv`, `invoices.csv`, `cmdb.json`, `cloud.json`, `repos.json`, `catalog.json`, …) are written",
             "to `data/{tenant}/raw/`. After writing the tables the generator builds the knowledge graph and runs every agent once",
             "(baseline, trigger `scheduled`) plus a small set of historical decisions (`backend/app/services/bootstrap.py`).", "",
             "## Tables and volumes", "", "| Table | NorthGrid | Meridian | Notes |", "|---|---|---|---|"]
    notes = {"gt_app_aliases": "hidden ground truth: raw name → application", "gt_shadow_it": "hidden ground truth: shadow IT",
             "gt_planted": "hidden ground truth: every planted anomaly", "kg_nodes": "knowledge graph", "kg_edges": "knowledge graph",
             "agent_runs": "baseline runs", "approvals": "baseline proposals + history", "audit_events": "", "tickets": "simulated Jira"}
    rn, rm = Repo("northgrid"), Repo("meridian")
    for t in models.metadata.tables:
        if t in ("tenants", "meta_kv", "agent_settings"):
            continue
        lines.append(f"| `{t}` | {rn.count(t)} | {rm.count(t)} | {notes.get(t, '')} |")
    lines += ["", "## Planted anomalies (counts)", "", "| Anomaly | NorthGrid | Meridian |", "|---|---|---|"]
    cn = Counter(p["anomaly"] for p in rn.all("gt_planted"))
    cm = Counter(p["anomaly"] for p in rm.all("gt_planted"))
    for k in sorted(set(cn) | set(cm)):
        lines.append(f"| {k.replace('_', ' ')} | {cn.get(k, 0)} | {cm.get(k, 0)} |")
    lines += ["", "Every planted anomaly is listed with its subject record in table `gt_planted` and shown in the UI under",
              "**Ingested Sources → show what we planted**. Tests in `backend/tests/test_planted_anomalies.py` assert the ranges."]
    return "\n".join(lines) + "\n"


def gen_prompts(overwrite: bool = False) -> int:
    """Live-mode prompt per agent: role, inputs, finding schema, rules (+ shared rules from _common.md)."""
    import json

    from app.agents.registry import AGENTS

    pdir = ROOT / "backend" / "app" / "llm" / "prompts"
    common = (pdir / "_common.md").read_text()
    n = 0
    for a in AGENTS.values():
        path = pdir / f"{a.id}.md"
        if not a.runnable or (path.exists() and not overwrite):
            continue
        props = {k: v.get("type", v.get("anyOf", "")) for k, v in a.finding_model.model_json_schema().get("properties", {}).items()}
        path.write_text(
            f"# {a.name} (`{a.id}`)\n\n## Role\n{a.description}\n\n## Inputs\nTables read by the tool layer: {', '.join(a.inputs)}. "
            f"The user message contains the tool results as JSON: `facts` and `findings` (typed `{a.outputs}`, each with `source_refs`).\n\n"
            f"## Finding schema (already computed — do not change values)\n```json\n{json.dumps(props, indent=1, default=str)}\n```\n\n"
            f"## What to write\n- A summary a {a.approver_role or 'principal architect'} can act on, leading with the most material finding.\n"
            f"- Rank findings by business impact (risk, money, deadline) in `order`.\n"
            f"- Optionally add up to 5 `notes`, each citing that finding's record ids.\n"
            f"- Proposed actions ({', '.join(a.action_types) or 'none'}) are created by the platform; never claim anything is approved.\n\n{common}")
        n += 1
    return n


def main() -> None:
    gen_prompts()
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "AGENT_CATALOG.md").write_text(catalog_markdown())
    (ROOT / "docs" / "DEMO_SCRIPT.md").write_text(demo_script())
    (ROOT / "data_gen" / "README.md").write_text(data_readme())
    print("wrote docs/AGENT_CATALOG.md, docs/DEMO_SCRIPT.md, data_gen/README.md")


if __name__ == "__main__":
    main()
